Event region message defaults
geosolutions-it/mapstore-events-tracker pull request #8
Opened 2021-12-06 16:57 UTC by timkeane

default messages and config reflect the event/region model

2021-12-06 16:58 UTC, timkeane commented
This is ready for a 1.0.3 patch release

2021-12-06 17:46 UTC, cmenedes commented
This is ready for a 1.0.3 patch release. Needs to be merged upon review

2021-12-07 09:49 UTC, allyoucanmap requested changes

2021-12-07 09:49 UTC, allyoucanmap commented on configs/localConfig.json
> +        "ov-translations"
The `ov-translations` are translations we add as override in a data dir but it would not work in the core as is now.
I would not include this in the current PR but meaby we could discuss how to add this keeping the create script consistent with this new folder.

2021-12-07 09:50 UTC, allyoucanmap commented
@timkeane @cmenedes 
Sorry I just published a 1.0.3 version with the fix in the master
I'll publish a new version after the merge (1.0.4)

2021-12-10 15:16 UTC, allyoucanmap commented on configs/localConfig.json
> +        "ov-translations"
```suggestion
        "translations"
```

2021-12-10 15:17 UTC, allyoucanmap approved these changes

2021-12-10 15:18 UTC, merged